<?php
class AppError extends ErrorHandler {

function anyerror(){
?>
<h1>Bromine Error</h1>
<h2>PLEASE COPY/PASTE ALL THE FOLLOWING INTO JIRA ISSUE AT 
<a href='http://jira.openqa.org/browse/BR'>http://jira.openqa.org/browse/BR</a>
<br>THANKS FOR YOUR COOPERATION</h2>

<h3>Autogenerated error report:</h3>
<p>
<?php echo $this->pageTitle; ?>
<br>
Time: <?php echo date("D M j G:i:s T Y"); ?>
</p>
<pre>
<?php

$debug = print_r($this,true);
$debug = htmlspecialchars($debug);
//echo $this['name'];
echo($debug);
?>
</pre>

<?php
}

}	
?>